'use client';
import { type ButtonHTMLAttributes, type ReactNode } from 'react';
import { ArrowLeft, ArrowUpRight, Check } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
function cx(...classes:(string|false|null|undefined)[]){return classes.filter(Boolean).join(' ')}
export function Screen({onBack,right,cta,children,scene,className=''}:{onBack?:()=>void;right?:ReactNode;cta?:ReactNode;children:ReactNode;scene?:ReactNode;className?:string}){return <div className={`experience-screen ${scene?'has-scene':''} ${className}`}><div className="experience-toolbar">{onBack?<button onClick={onBack} className="back-button"><ArrowLeft size={16}/> 이전으로</button>:<span>ABIB / YOUR MOMENT</span>}<div>{right}</div></div><div className="experience-layout"><main className="experience-controls"><div className="controls-content">{children}</div>{cta&&<div className="experience-cta">{cta}</div>}</main>{scene&&<aside className="experience-scene">{scene}</aside>}</div></div>}
type ButtonProps=ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'primary'|'weak'|'ghost';size?:'lg'|'md'};
export function Button({variant='primary',size='lg',className,children,...props}:ButtonProps){return <button {...props} className={cx('action-button',`button-${variant}`,`button-${size}`,className)}>{children}{variant==='primary'&&<ArrowUpRight className="button-arrow" size={19}/>}</button>}
export function Title({eyebrow,children,sub,english}:{eyebrow?:string;children:ReactNode;sub?:ReactNode;english?:string}){return <div className="flow-title">{eyebrow&&<p className="eyebrow">{eyebrow}</p>}{english?<><h1 className="english-title">{english}</h1><h2 className="korean-title">{children}</h2></>:<h1 className="korean-heading">{children}</h1>}{sub&&<p className="flow-sub">{sub}</p>}</div>}
export function ChoiceList<T extends string|number>({label,value,onChange,options}:{label:string;value:T;onChange:(v:T)=>void;options:{value:T;title:ReactNode;desc?:ReactNode;leading?:ReactNode;disabled?:boolean;badge?:string}[]}){return <RadioGroup aria-label={label} value={String(value)} onValueChange={v=>{const o=options.find(o=>String(o.value)===v);if(o)onChange(o.value)}} className="choice-list">{options.map((o,i)=><label key={String(o.value)} className={cx('choice-row',value===o.value&&'selected',o.disabled&&'unavailable')}><span className="choice-index">0{i+1}</span>{o.leading}<span className="choice-text"><strong>{o.title}</strong>{o.desc&&<small>{o.desc}</small>}</span>{o.badge&&<span className="choice-badge">{o.badge}</span>}<RadioGroupItem value={String(o.value)} disabled={o.disabled}/></label>)}</RadioGroup>}
export function Notice({children,tone='info'}:{children:ReactNode;tone?:'info'|'error'}){return <p role={tone==='error'?'alert':undefined} className={`notice notice-${tone}`}>{children}</p>}
export function Field({label,children,hint}:{label:string;children:ReactNode;hint?:ReactNode}){return <label className="form-field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
export const inputClass='editor-input';
export function Sheet({open,onClose,title,description,children}:{open:boolean;onClose:()=>void;title:ReactNode;description?:ReactNode;children?:ReactNode}){return <Dialog open={open} onOpenChange={v=>{if(!v)onClose()}}><DialogContent className="brand-dialog"><DialogTitle className="brand-dialog-title">{title}</DialogTitle><DialogDescription className={description?'brand-dialog-copy':'sr-only'}>{description||'체험을 계속하거나 닫을 수 있어요.'}</DialogDescription><div className="dialog-actions">{children}</div></DialogContent></Dialog>}
export function QrCard({qr,title,desc}:{qr:string;title:string;desc:string}){return <div className="qr-card">{qr?<img src={qr} alt="휴대폰으로 스캔해서 열기"/>:<span>공유 버튼으로<br/>링크를 가져가세요.</span>}<div><p>{title}</p><small>{desc}</small></div></div>}
export function StepCount({step,total}:{step:number;total:number}){return <div className="step-count"><span>STEP {String(step).padStart(2,'0')}</span><div aria-hidden="true">{Array.from({length:total},(_,i)=><i key={i} className={i<step?'filled':''}/>)}</div><small>{String(total).padStart(2,'0')}</small></div>}
