'use client';
import { useState, type CSSProperties, type ReactNode } from 'react';
import { LabelDesign } from '@/components/label-design';
import { FRAMES, LABEL_COLORS, PRODUCTS, type LabelStyle } from '@/lib/moments';

export function Bottle({ word = 'MYCALM', color = 0, product = 0, className = '', labelStyle='frosted' }: { labelStyle?:LabelStyle; word?: string; color?: number; product?: number; className?: string }) {
 const c=LABEL_COLORS[color]||LABEL_COLORS[0],p=PRODUCTS[product]||PRODUCTS[0];
 return <div className={`bottle-object ${className}`}><img src="/images/serum.png" alt="아비브 세럼 콘셉트 패키지" draggable={false}/><div className={`bottle-label designed-label ${labelStyle}`}><LabelDesign style={labelStyle} word={word} color={color} product={product}/></div></div>
}
export function PhotoStrip({shots=[],frame=0,className=''}:{shots?:string[];frame?:number;className?:string}){const f=FRAMES[frame]||FRAMES[0];return <div className={`photo-strip ${className}`} style={{background:f.bg,color:f.text}}><div className="strip-inner">{[0,1,2].map(i=><div className="strip-photo" key={i}><img src={shots[i]||'/images/portrait.webp'} alt={shots[i]?`사진 ${i+1}`:''} draggable={false} style={shots[i]?undefined:{objectPosition:`${45+i*5}% ${30+i*15}%`,transform:i===1?'scaleX(-1) scale(1.08)':i===2?'scale(1.2)':'',filter:i===1?'grayscale(1)':''}}/></div>)}<div className="strip-signature">Abib<span>CALM<br/>WEEKEND</span></div><p>YOUR PACE LOOKS GOOD ON YOU.</p></div></div>}
export function ProductStage({product=0,color=0,word='MYCALM',complete=false,labelStyle='frosted'}:{labelStyle?:LabelStyle;product?:number;color?:number;word?:string;complete?:boolean}){
 const [tilt,setTilt]=useState({x:-7,y:-9});
 return <div className={`product-world ${complete?'is-complete':''}`} style={{'--label-tone':LABEL_COLORS[color].hex,'--rx':tilt.x+'deg','--ry':tilt.y+'deg'} as CSSProperties} onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();setTilt({x:((e.clientY-r.top)/r.height-.5)*-12,y:((e.clientX-r.left)/r.width-.5)*28})}} onPointerLeave={()=>setTilt({x:-7,y:-9})}><div className="world-top"><span>Abib / PERSONAL LABEL STUDIO</span><span>0{product+1}</span></div><div className="world-large-word" aria-hidden="true">{complete?'yours.':'only you.'}</div><div className="product-sculpture"><Bottle product={product} color={color} word={word} labelStyle={labelStyle}/></div><div className="world-bottom"><div><small>YOUR ESSENTIAL</small><h3>{PRODUCTS[product].label.toLowerCase()}</h3><span>{labelStyle==='signature'?'SIGNATURE':'FROSTED'} / {word}</span></div><span className="world-instruction">{complete?'MADE BY YOU.':'움직여서 살펴보기 ↔'}</span></div><div className="world-annotation"><span>LESS, BUT BETTER.</span><span>30 ML — YOUR OWN EDITION</span></div></div>
}
export function PhotoStage({shots=[],frame=0,printing=false,children}:{shots?:string[];frame?:number;printing?:boolean;children?:ReactNode}){return <div className={`photo-world ${printing?'is-printing':''}`}><div className="world-top"><span>Abib / THE CALM PHOTOBOOTH</span><span>01</span></div><div className="photo-world-heading" aria-hidden="true">stay<br/><em>a little.</em></div>{children?<div className="live-stage">{children}</div>:<div className="print-window"><div className="print-edge"/><div className="printed-moment"><PhotoStrip shots={shots} frame={frame}/></div></div>}<div className="photo-world-note"><span>지금의 너를, 그대로.</span><strong>A little moment.<br/>A softer memory.</strong></div><div className="world-annotation"><span>THREE FRAMES. ALL YOU.</span><span>CALM WEEKEND / SINGAPORE</span></div></div>}
